language: dart
sudo: false
dart:
  - stable
  - dev
dart_task:
- test: --platform vm
- test: --platform chrome
- dartanalyzer: --fatal-warnings lib test


services:
  - docker

before_script:
  - sysctl -w vm.max_map_count=262144
  - docker-compose up -d
  - until curl "http://localhost:7512/?pretty"; do sleep 10; done
  - ./adminauth.sh
  - pub get

after_success:
  - if [ "$TRAVIS_DART_VERSION" == "stable" ]; then ./coverage.sh; fi
  - if [ "$TRAVIS_DART_VERSION" == "stable" ]; then dartdoc; fi

cache:
  directories:
    - $HOME/.pub-cache

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: doc/api
  on:
    branch: master
    dart: stable