language: dart
sudo: false
dart:
  - stable
  - dev
dart_task:
- test: --platform vm
- dartanalyzer: --fatal-warnings lib
- dartfmt

services:
  - docker

before_script:
  - if [ $TRAVIS_DART_TEST == true ]; then ./docker_launch.sh; fi

cache:
  directories:
    - $HOME/.pub-cache

after_success:
  - if [ "$TRAVIS_DART_VERSION" == "stable" ] && [ $TRAVIS_DART_TEST == true ]; then ./coverage.sh; fi
  - if [ "$TRAVIS_DART_VERSION" == "stable" ] && [ $TRAVIS_DART_TEST == true ] && [ $TRAVIS_BRANCH == 'master' ]; then dartdoc; fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: doc/api
  on:
    branch: master
    dart: stable
    condition: $TRAVIS_DART_TEST == true