language: dart
sudo: false
dart:
  - stable
  - dev

services:
  - docker

before_script:
  - sysctl -w vm.max_map_count=262144
  - docker-compose up -d
  - until curl "http://localhost:7512/?pretty"; do sleep 10; done
  - ./adminauth.sh
  - pub get

script:
  - dartanalyzer lib test --fatal-warnings
  - pub run test

after_success:
  - ./coverage.sh
  - dartdoc

cache:
  directories:
    - $HOME/.pub-cache

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: doc/api
  on:
    branch: master
    dart: stable