language: dart
sudo: false
dart:
  - stable
  - dev
dart_task:
- test: --platform vm
- test: --platform chrome
- dartanalyzer: --fatal-warnings lib test
- dartfmt

services:
  - docker

before_script:
  - if [ $TRAVIS_DART_TEST == true ]; then ./kuzzle_docker.sh; fi

after_success:
  - if [ "$TRAVIS_DART_VERSION" == "stable" ] && [ $TRAVIS_DART_TEST == true ]; then ./coverage.sh; fi
  - if [ "$TRAVIS_DART_VERSION" == "stable" ] && [ $TRAVIS_DART_TEST == true ]; then dartdoc; fi

cache:
  directories:
    - $HOME/.pub-cache

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: doc/api
  on:
    branch: master
    dart: stable