language: dart
sudo: false
dart: dev

before_install:
  - pub global activate test_coverage
  - gem install coveralls-lcov

script:
  - test_coverage
  - dartanalyzer lib --fatal-infos --fatal-warnings

after_success:
  - coveralls-lcov coverage/lcov.info
  - dartdoc

cache:
  directories:
    - $HOME/.pub-cache

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: doc/api
  on:
    branch: master