language: dart
sudo: false
dart: dev

script:
  - dartanalyzer lib test --fatal-warnings
  - pub run test_coverage -j 1

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - dartdoc

cache:
  directories:
    - $HOME/.pub-cache

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: doc/api
  on:
    branch: master