name: kuzzle
version: 1.0.0-alpha.1

description: A library to communicate with kuzzle API
authors:
- Priyanshu Jindal<priyanshujindal1995@gmail.com>
- Sacha Stafyniak<sacha.stafyniak@gmail.com>
homepage: https://github.com/prijindal/kuzzle_dart

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  meta: ^1.1.7
  uuid: ^1.0.3

dev_dependencies:
  test: ^1.5.1+1
  coverage: ^0.12.3
